//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8000/CatalogService", ConfigurationName="ICatalogServiceContract")]
public interface ICatalogServiceContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/CatalogService/ICatalogServiceContract/GetBookByIsbn", ReplyAction="http://localhost:8000/CatalogService/ICatalogServiceContract/GetBookByIsbnRespons" +
        "e")]
    string GetBookByIsbn(string isbn);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICatalogServiceContractChannel : ICatalogServiceContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CatalogServiceContractClient : System.ServiceModel.ClientBase<ICatalogServiceContract>, ICatalogServiceContract
{
    
    public CatalogServiceContractClient()
    {
    }
    
    public CatalogServiceContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CatalogServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CatalogServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CatalogServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetBookByIsbn(string isbn)
    {
        return base.Channel.GetBookByIsbn(isbn);
    }
}
